FROM kalilinux/kali-rolling

# NOTE: openssl has to be installed before pycurl, and pycurl before wfuzz. 
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y libcurl4-openssl-dev libssl-dev python3-pip && \
    pip install pycurl && \
    apt-get install -y metasploit-framework wfuzz vim iproute2 iputils-ping

# prevent container from stopping
CMD ["tail", "-f", "/dev/null"]